---
title: "Calculating log-likelihood for a bivariate linear mixed effects model"
author: "Frederick Boehm"
date: "`r lubridate::now()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculating log-likelihood for a bivariate linear mixed effects model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Vignettes are long form documentation commonly included in packages. Because they are part of the distribution of the package, they need to be as compact as possible. The `html_vignette` output type provides a custom style sheet (and tweaks some options) to ensure that the resulting html is as small as possible. The `html_vignette` format:

- Never uses retina figures
- Has a smaller default figure size
- Uses a custom CSS stylesheet instead of the default Twitter Bootstrap style


## Figures

The figure sizes have been customised so that you can easily put two images side-by-side. 

```{r, fig.show='hold'}
plot(1:10)
plot(10:1)
```

You can enable figure captions by `fig_caption: yes` in YAML:

    output:
      rmarkdown::html_vignette:
        fig_caption: yes

Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**.

## The linear mixed effects model

$$ vec(Y) = XB + vec(G) + vec(E)$$ where $Y$ is a n by 2 matrix of phenotypes, with one row per subject and one column per trait, $X$ is a 2n by 2f block diagonal matrix consisting of two n by f matrices, one for each of two loci. $n$ is the number of subjects and $f$ is the number of founders. $G$ is a n by 2 matrix of random effects, with $$G \sim MN(0, K, Vg)$$ where $MN(0, K, Vg)$ denotes the matrix-variate normal distribution with mean zero, row covariance $K$ and column covariance $Vg$. 


